name: Python application

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # "docker compose" won't run without this step.
    - uses: actions/checkout@v3
    
    - name: run tests
      run: |
        docker compose run pytest
